### ISSUE TITLE
Aggiungere altri CdL del DISI

### ISSUE THREAD

**Issue by foxyseta** [csunibo/course-description-merged#21]
Idealmente potremmo espanderlo a tutti i CdL del DISI, o anche solo a quelli già presenti su Dynamik. @gabrielegenovese cosa ne pensi?

**Comment by gabrielegenovese** [comment]
Si, basta renderlo dinamico per l'indirizzo del piano di studi. L'unico problema potrebbe presentarsi è sulla gestione delle accezioni che andrebbero gestite manualmente

**Comment by foxyseta** [comment]
Eccezioni gestite manualmente? Tipo quali?

**Comment by gabrielegenovese** [comment]
Il tool è pensato per dare la descrizione in inglese di tutte le materie e i suoi contenuti. Però nel piano di studi alcune materie non hanno i titoli del corso tradotti, quindi nel tool sono state aggiunte a mano le traduzioni di alcuni corsi. Questa feature da generalizzare è di difficile implementazione, però si può chiedere all'utente oppure dare semplicemente il documento e lo modifica l'utente.

**Comment by foxyseta** [comment]
Sì io darei il documento. Offriamo già .md, .tex e .html o qualcosa di simile.

**Comment by foxyseta** [comment]
Possiamo fare scraping da qui per il corso dei CdL: https://disi.unibo.it/it/didattica/corsi
