### ISSUE TITLE
Scraper rotto

### ISSUE THREAD

**Issue by foxyseta** [csunibo/course-description-merged#41]
A una certa lo scraper si è rotto e ora dà output vuoto (riesco a riprodurlo anche in locale: non è un problema solo di produzione).

Potrebbe essere il preterso giusto per pensare anche a #17, #21 e #47.

@gabrielegenovese tu (se ricordo bene) e io siamo pieni di lavoro al momento ma mi piacerebbe riprendere in mano Rust a una certa quindi in futuro non escludo di lavorarci io. La gente usa il comando `/tesi` nei gruppi? Perché se sì, sarebbe carino che questo scraper tornasse a funzionare a breve.

I messaggi di errore incriminati sono probabilmente:
```
Cannot get course description: Cannot parse course title
```

**Comment by gabrielegenovese** [comment]
Direi che rispetto a progetti come polleg e csgitbot, questo non è prioritario.

Se qualcuno ha voglia di dare una mano lato programmazione può prendersi #21 #40, invece lato CI #17.

**Comment by samuelemusiani** [comment]
Ho fixato io senza vedere la issue ahaha
e5952dc3d2b1ba17ff6e5c8636ded10b323622f5

**Comment by foxyseta** [comment]
Magico lui
